//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by BlogToBook.rc
//
#define IDSAVE                          3
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_BlogToBookTYPE              130
#define IDR_PASTE_MENU                  151
#define IDR_WINDOWS_MENU                152
#define ID_VIEW_NAVIGATION              185
#define IDB_NAVIGATION_LARGE            186
#define IDB_NAVIGATION_LARGE_HC         187
#define IDB_PAGES                       188
#define IDB_PAGES_HC                    189
#define IDB_PAGES_SMALL                 190
#define IDB_PAGES_SMALL_HC              191
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define ID_TOOLS_OPTIONS                220
#define ID_VIEW_CAPTION_BAR             221
#define IDB_INFO                        230
#define IDS_CAPTION_BUTTON              231
#define IDS_CAPTION_BUTTON_TIP          232
#define IDS_CAPTION_TEXT                233
#define IDS_CAPTION_IMAGE_TIP           234
#define IDS_CAPTION_IMAGE_TEXT          235
#define IDS_MYCALENDARS                 250
#define IDS_CALENDAR                    251
#define IDS_SHORTCUTS                   252
#define IDS_FOLDERS                     253
#define IDS_OUTLOOKBAR                  258
#define IDS_EDIT_MENU                   306
#define IDR_RIBBON                      307
#define ID_ARTICLE_LIST                 308
#define IDD_DIALOG_ATTRIB               311
#define IDD_DIALOG_NEW_PROJECT          313
#define IDD_DIALOG_SHOWCASE             315
#define IDC_EDIT_ATT_HEAD               1000
#define IDC_CHECK_ATT_INCULDE           1001
#define IDC_EDIT_ATT_CONTENT            1002
#define IDC_EDIT_PROJNAME               1003
#define IDC_EDIT_PROJFOLDER             1004
#define IDC_BUTTON_PROJBROWSE           1005
#define IDC_BUTTON_PROJOPEN             1006
#define IDC_EDIT_SC_PLINK               1006
#define IDC_EDIT_SC_TAGS                1007
#define IDC_EDIT_SC_COMMENTS            1008
#define IDC_BUTTON_SC_VISIT             1009
#define IDC_SC_TCLINK                   1010
#define IDC_CHECK1                      1011
#define IDC_CHECK_TERMS                 1011
#define IDC_BUTTON_SC_UPLOAD            1012
#define IDC_PROGRESS_SC                 1013
#define IDC_BUTTON_SC_REM               1014
#define IDC_LIST_SCDATA                 1019
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_BUTTON_FETCH                 32771
#define ID_BUTTON_RENDER                32772
#define ID_COMBO_FONT_TITLE             32773
#define ID_COMBO_FONT_BODY              32774
#define ID_SPIN_TITLE_SIZE              32775
#define ID_SPIN_BODY_SIZE               32776
#define ID_SLIDER_PAGESCALE             32777
#define ID_EDIT_ZOOM                    32779
#define ID_BUTTON_FIT                   32780
#define ID_BUTTON3                      32781
#define ID_BUTTON_SAVEEPUB              32781
#define ID_EDIT_FETCHFROM               32782
#define ID_EDIT_FETCHTO                 32783
#define ID_EDIT_ADDR                    32784
#define ID_EDIT_BNAME                   32785
#define ID_EDIT_AUTH                    32786
#define ID_BUTTON_DEMO                  32787
#define ID_BUTTON_LIST                  32788
#define ID_BUTTON_SHOWFOLDER            32789
#define ID_BUTTON_SHOWCASE              32790
#define ID_BUTTON_VALID                 32791
#define ID_EDIT_BOOK_TITLE              32792
#define ID_EDIT_BOOK_DESC               32793
#define ID_EDIT_BOOK_PUB                32794
#define ID_EDIT_BOOK_PUBDATE            32795
#define ID_EDIT_BOOK_LANG               32796
#define ID_EDIT_BOOK_ISBN               32797
#define ID_BUTTON_LIC                   32798
#define ID_BUTTON_COVER                 32799
#define ID_BUTTON_PREFACE               32800
#define ID_BUTTON_ENDPAGE               32801
#define ID_CHECK_REF                    32802
#define ID_BUTTON_DED                   32803
#define ID_BUTTON_EDLIST                32804
#define ID_BUTTON_CALIBRE               32805
#define ID_BUTTON_RESET_FONT            32810
#define ID_BUTTON_HELP                  32811
#define ID_BUTTON_UPDATE                32812

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        318
#define _APS_NEXT_COMMAND_VALUE         32813
#define _APS_NEXT_CONTROL_VALUE         1020
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
